import { randomBytes } from 'node:crypto';
import { prisma, withTenantTx } from '@seredina/db';
import { CHAT_WEBHOOK_EVENTS, encryptSecret, type WebhookEvent, type WebhookKind } from '@seredina/shared';

function validateEventsForKind(kind: WebhookKind, events: WebhookEvent[]) {
  if (kind === 'generic') return;
  const invalid = events.filter((e) => !(CHAT_WEBHOOK_EVENTS as readonly string[]).includes(e));
  if (invalid.length > 0) {
    throw new Error(`${kind} webhooks only support these events: ${CHAT_WEBHOOK_EVENTS.join(', ')} (got: ${invalid.join(', ')})`);
  }
}

const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY;
if (!ENCRYPTION_KEY) {
  throw new Error('ENCRYPTION_KEY env var is required');
}

// Never select secretEncrypted back out -- same reasoning as EmailChannel's
// SAFE_SELECT. The plaintext secret is shown exactly once, in createWebhook's
// return value, and never again -- same shape as ApiKey, except a webhook's
// secret also has to be recoverable later (to sign every delivery), which is why
// it's encrypted rather than hashed.
const SAFE_SELECT = {
  id: true,
  kind: true,
  url: true,
  events: true,
  isActive: true,
  createdAt: true,
  lastDeliveryAt: true,
  lastDeliveryStatus: true,
} as const;

export async function listWebhooks(tenantId: string) {
  return withTenantTx(prisma, tenantId, (tx) =>
    tx.webhook.findMany({ select: SAFE_SELECT, orderBy: { createdAt: 'desc' } }),
  );
}

export interface CreateWebhookInput {
  url: string;
  events: WebhookEvent[];
  kind?: WebhookKind;
}

/**
 * A 'slack'/'teams' kind webhook needs no signing secret -- neither platform's
 * own webhook mechanism has an HMAC-verification concept, the URL itself
 * (generated by the tenant in their own workspace) is the only credential. Only
 * 'generic' (the default, a tenant's own receiver) gets one. See
 * docs/adr/0048-chat-notifications.md.
 */
export async function createWebhook(tenantId: string, input: CreateWebhookInput) {
  if (!input.url.startsWith('https://')) {
    throw new Error('webhook URL must use https://');
  }
  const kind = input.kind ?? 'generic';
  validateEventsForKind(kind, input.events);

  const secret = kind === 'generic' ? randomBytes(32).toString('hex') : null;
  const secretEncrypted = secret ? encryptSecret(secret, ENCRYPTION_KEY!) : null;

  const webhook = await withTenantTx(prisma, tenantId, (tx) =>
    tx.webhook.create({
      data: { tenantId, kind, url: input.url, events: input.events, secretEncrypted },
      select: SAFE_SELECT,
    }),
  );

  return { ...webhook, secret };
}

export async function deleteWebhook(tenantId: string, id: string) {
  return withTenantTx(prisma, tenantId, async (tx) => {
    const existing = await tx.webhook.findUnique({ where: { id } });
    if (!existing) throw new Error('webhook not found');
    await tx.webhook.delete({ where: { id } });
  });
}

export interface UpdateWebhookInput {
  url?: string;
  events?: WebhookEvent[];
  isActive?: boolean;
}

/**
 * Never touches secretEncrypted -- rotating the signing secret is its own
 * explicit action (rotateWebhookSecret below), not a side effect of editing
 * the URL or event list. A plain "edit" changing the secret out from under an
 * operator who didn't ask for that would silently break their delivery
 * verification.
 */
/** kind is set at creation and never changes -- events are re-validated against the existing row's own kind, not the request. */
export async function updateWebhook(tenantId: string, id: string, input: UpdateWebhookInput) {
  if (input.url && !input.url.startsWith('https://')) {
    throw new Error('webhook URL must use https://');
  }
  return withTenantTx(prisma, tenantId, async (tx) => {
    const existing = await tx.webhook.findUnique({ where: { id } });
    if (!existing) throw new Error('webhook not found');
    if (input.events) validateEventsForKind(existing.kind as WebhookKind, input.events);
    return tx.webhook.update({
      where: { id },
      data: { url: input.url, events: input.events, isActive: input.isActive },
      select: SAFE_SELECT,
    });
  });
}

/** Shown once, exactly like createWebhook's -- the old secret stops verifying deliveries immediately. Only 'generic' webhooks have a secret to rotate. */
export async function rotateWebhookSecret(tenantId: string, id: string) {
  const secret = randomBytes(32).toString('hex');
  const secretEncrypted = encryptSecret(secret, ENCRYPTION_KEY!);

  const webhook = await withTenantTx(prisma, tenantId, async (tx) => {
    const existing = await tx.webhook.findUnique({ where: { id } });
    if (!existing) throw new Error('webhook not found');
    if (existing.kind !== 'generic') throw new Error(`${existing.kind} webhooks have no signing secret to rotate`);
    return tx.webhook.update({ where: { id }, data: { secretEncrypted }, select: SAFE_SELECT });
  });

  return { ...webhook, secret };
}
